class INeuralNetwork:
    def copyToInput(self, _: "<-", region, src, stream): ...
    def copyFromInput(self, region, stream, _: "->", dst): ...
    def copyFromOutput(self, region, stream, _: "->", dst): ...
    def copyToInputFromHost(self, _: "<-", region, src, stream): ...
    def copyToInputFromLong(self, _: "<-", region, value, stream): ...

    def forward(self, x, stream, _: "->", y, fw_trace_for_bw): ...
    def backward(self, fw_trace_for_bw, t, stream, _: "->", buf_tC, buf_hp): ...

    def getHyperparameters(self): ...

    def setTarget(self, _: "<-", region, src, stream): ...
    def computeOutputGradient(self, _: "<-", currentOutput, region, stream): ...
    def injectOutputGradient(self, _: "<-", region, gradC, stream): ...
    def copyFromInputGradient(self, region, stream, _: "->", dst): ...
    def gradientToInput(self, _: "<-", gradC, inputC, stream): ...
    def injectOutputGradientFromInputGradient(self, _: "<-", region, stream): ...
    def gradientToInputFromInternal(self, _: "<-", region, inputC, stream): ...
    def zeroGradient(self, stream, _: "->", gradVec): ...
    def zeroVector(self, stream, _: "->", vec): ...

    def createVector(self, size): ...
    def createGradientVector(self, size): ...

    def save(self, folderPath): ...
    def loadVector(self, path): ...
    def loadGradientVector(self, path): ...
    def encodingProfile(self): ...

    def close(self): ...
