class INeuralNetwork:
    def copyToInput(self, _: "<-", region, src, stream): ...
    def copyFromInput(self, region, stream, _: "->", dst): ...
    def copyFromOutput(self, region, stream, _: "->", dst): ...
    def copyToInputFromHost(self, _: "<-", region, src, stream): ...
    def copyToInputFromLong(self, _: "<-", region, value, stream): ...

    def forward(self, x, stream, _: "->", y, fwTraceForBw): ...
    def backward(self, fwTraceForBw, t, stream, _: "->", bufTc, bufHp): ...

    def getHyperparameters(self): ...

    def setTarget(self, _: "<-", region, src, stream): ...
    def computeOutputGradient(self, _: "<-", currentOutput, region, stream): ...
    def injectOutputGradient(self, _: "<-", region, gradC, stream): ...
    def copyFromInputGradient(self, region, stream, _: "->", dst): ...
    def gradientToInput(self, _: "<-", gradC, inputC, stream): ...
    def injectOutputGradientFromInputGradient(self, _: "<-", region, stream): ...
    def gradientToInputFromInternal(self, _: "<-", region, inputC, stream): ...
    def zeroGradient(self, stream, _: "->", gradVec): ...
    def zeroVector(self, stream, _: "->", vec): ...

    def createVector(self, size): ...
    def createGradientVector(self, size): ...

    # 创建前向 trace（供反向使用）。伪代码接口原未声明但 urana 映射器调用，补入。
    def createFwTraceForBw(self): ...

    def save(self, folderPath): ...
    def loadVector(self, path): ...
    def loadGradientVector(self, path): ...
    def encodingProfile(self): ...

    # 感觉载体契约（可选能力）：创建本 nn 家族的感觉缓冲区。
    # 载体类型由 nn 家族定义（BNN→BoolVector，CNN→FloatVector），长度由上层 domain 传入——
    # 载体类型知识不离开 nn 家族，上层只拿到产品（缓冲实例），无类型开关（真善美第2条）。
    def newFeelingBuffer(self, feelingLength): ...

    # 视觉解码器契约（可选能力）：快照纹理 → 本家族感觉缓冲的解码器。
    def newVisionEncoder(self): ...

    # 行为载体契约（可选能力）：创建本 nn 家族的行为缓冲区。
    def newBehaviorBuffer(self, behaviorLength): ...

    # 行为读取契约（可选能力）：把行为缓冲区的载体数据读出到 int[]（effector 期望的 bit-packed 格式）。
    # BNN 直接从 mapped host 内存读 int[]（零拷贝）；
    # CNN 读 float[] 后阈值化为 bit 再打包为 int[]（float→bit 转换是 CNN 家族的内部模式）。
    def readBehaviorTo(self, behaviorBuffer, dst, stream): ...

    def close(self): ...