class Span:
    def __init__(self, offset, length):
        self.offset = offset
        self.length = length

    def getOffset(self):
        return self.offset

    def getLength(self):
        return self.length


class VectorBase:
    def __init__(self, size):
        self.size = size

    def copyRegionFrom(self, _: "<-", src, srcSpan, dstSpan, stream): ...
    def save(self, path): ...
    def close(self): ...
    def size(self):
        return self.size


class BoolVector(VectorBase):
    def setRegion(self, _: "<-", region, src, stream): ...
    def copyRegionFromHost(self, _: "<-", region, src, stream): ...
    def fillRandom(self, _: "<-", seedOrBound, seed=None): ...
    def requireHandle(self): ...
    def get(self, index): ...
    def set(self, index, value): ...

    @staticmethod
    def loadFromFile(path): ...


class IntVector(VectorBase):
    def setRegion(self, _: "<-", region, src, stream): ...
    def multiplyByScalar(self, _: "<-", scalar, span=None, stream=None): ...
    def fillRandom(self, _: "<-", bound, seed): ...
    def requireHandle(self): ...
    def get(self, index): ...
    def set(self, index, value): ...

    @staticmethod
    def loadFromFile(path): ...


class FloatVector(VectorBase):
    def setRegion(self, _: "<-", region, src, stream): ...
    def multiplyByScalar(self, _: "<-", scalar, span=None, stream=None): ...
    def fillRandom(self, _: "<-", bound, seed): ...
    def requireHandle(self): ...
    def get(self, index): ...
    def set(self, index, value): ...

    @staticmethod
    def loadFromFile(path): ...


class Stream:
    def __init__(self): ...
    def waitEvent(self, _: "<-", event): ...
    def requireHandle(self): ...
    def close(self): ...


class Event:
    def __init__(self): ...
    def record(self, _: "<-", stream): ...
    def close(self): ...


class MappedGenerationBuffer:
    def __init__(self, buffer): ...
    def getBuffer(self): ...
    def publish(self, _: "<-", stream): ...


class SaveSlot:
    def __init__(self, rootPath):
        self.rootPath = rootPath

    def layerPath(self, layer): ...