class FittableMapper:
    def assembleX(self, C, F, G, dt, stream, _: "->", buf_x): ...
    def assembleT(self, C, F, B, stream, _: "->", buf_t): ...
    def fw(self, x, stream, _: "->", y, fw_trace_for_bw): ...
    def bw(self, fw_trace_for_bw, t, stream, _: "->", buf_tC, buf_mapper): ...

    def zeroGradient(self, stream, _: "->", gradVec): ...
